import type { Metadata } from 'next'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="mx-auto w-full pt-8 pb-4 flex items-center justify-center">
          <Link href="/" className="mb-8 flex items-center justify-center text-center text-2xl font-black">ba3bos</Link>
        </header>
        {children}
      </body>
    </html>
  )
}
